In [5]:
import boto3 # type:  ignore 
import pandas as pd # type: ignore

In [6]:
s3 = boto3.client(
    "s3",
    endpoint_url="http://localstack:4566",
    aws_access_key_id="test",
    aws_secret_access_key="test",
    region_name="us-east-1"
)

In [7]:
s3.list_buckets()

{'ResponseMetadata': {'RequestId': 'f6c767e5-5785-469f-bb4e-c771603f895a',
  'HostId': 's9lzHYrFp76ZVxRcpX9+5cjAnEH2ROuNkd2BHfIa6UkFVdtjf5mKR3/eTPFvsiP/XV/VLi31234=',
  'HTTPStatusCode': 200,
  'HTTPHeaders': {'server': 'TwistedWeb/24.3.0',
   'date': 'Sat, 16 May 2026 17:25:35 GMT',
   'content-type': 'application/xml',
   'access-control-allow-origin': '*',
   'access-control-allow-methods': 'HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH',
   'access-control-allow-headers': 'authorization,cache-control,content-length,content-md5,content-type,etag,location,x-amz-acl,x-amz-content-sha256,x-amz-date,x-amz-request-id,x-amz-security-token,x-amz-tagging,x-amz-target,x-amz-user-agent,x-amz-version-id,x-amzn-requestid,x-localstack-target,amz-sdk-invocation-id,amz-sdk-request,x-amz-log-type',
   'access-control-expose-headers': 'etag,x-amz-version-id,x-amz-log-result,x-amz-executed-version,x-amz-function-error',
   'vary': 'Origin',
   'content-length': '375',
   'x-amz-request-id': 'f6c767e5-5785-469f-bb4e-c771603f895a',
   'x-amz-id-2': 's9lzHYrFp76ZVxRcpX9+5cjAnEH2ROuNkd2BHfIa6UkFVdtjf5mKR3/eTPFvsiP/XV/VLi31234='},
  'RetryAttempts': 0},
 'Buckets': [{'Name': 'ecommerce-lake',
   'CreationDate': datetime.datetime(2026, 5, 16, 17, 25, 30, tzinfo=tzlocal())}],
 'Owner': {'DisplayName': 'webfile',
  'ID': '75aa57f09aa0c8caeab4f8c24e99d10f8e7faeebf76c078efc7c6caea54ba06a'}}

In [8]:
objects = s3.list_objects_v2(
    Bucket="ecommerce-lake"
)

print(objects)

{'ResponseMetadata': {'RequestId': '27a5ece1-38d1-491b-9e57-c5ad68b75bd9', 'HostId': 's9lzHYrFp76ZVxRcpX9+5cjAnEH2ROuNkd2BHfIa6UkFVdtjf5mKR3/eTPFvsiP/XV/VLi31234=', 'HTTPStatusCode': 200, 'HTTPHeaders': {'server': 'TwistedWeb/24.3.0', 'date': 'Sat, 16 May 2026 17:25:35 GMT', 'content-type': 'application/xml', 'content-length': '519', 'x-amz-request-id': '27a5ece1-38d1-491b-9e57-c5ad68b75bd9', 'x-amz-id-2': 's9lzHYrFp76ZVxRcpX9+5cjAnEH2ROuNkd2BHfIa6UkFVdtjf5mKR3/eTPFvsiP/XV/VLi31234='}, 'RetryAttempts': 0}, 'IsTruncated': False, 'Contents': [{'Key': 'raw/data.csv', 'LastModified': datetime.datetime(2026, 5, 16, 17, 25, 30, tzinfo=tzlocal()), 'ETag': '"ddc07c6162f8da922e11c4009943d12b-6"', 'ChecksumAlgorithm': ['CRC32'], 'Size': 45580638, 'StorageClass': 'STANDARD'}], 'Name': 'ecommerce-lake', 'Prefix': '', 'MaxKeys': 1000, 'EncodingType': 'url', 'KeyCount': 1}

In [9]:
df = pd.read_csv(
    "s3://ecommerce-lake/raw/data.csv",
    encoding="latin1",
    storage_options={
        "key": "test",
        "secret": "test",
        "client_kwargs": {
            "endpoint_url": "http://localstack:4566"
        }
    }
)

/usr/local/lib/python3.11/site-packages/fsspec/registry.py:305: UserWarning: Your installed version of s3fs is very old and known to cause
severe performance issues, see also https://github.com/dask/dask/issues/10276

To fix, you should specify a lower version bound on s3fs, or
update the current installation.

  warnings.warn(s3_msg)

In [10]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

In [11]:
df.nunique()

InvoiceNo      25900
StockCode       4070
Description     4223
Quantity         722
InvoiceDate    23260
UnitPrice       1630
CustomerID      4372
Country           38
dtype: int64

In [12]:
df.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [18]:
df.describe().round(2)

        Quantity  UnitPrice  CustomerID
count  541909.00  541909.00   406829.00
mean        9.55       4.61    15287.69
std       218.08      96.76     1713.60
min    -80995.00  -11062.06    12346.00
25%         1.00       1.25    13953.00
50%         3.00       2.08    15152.00
75%        10.00       4.13    16791.00
max     80995.00   38970.00    18287.00