In [10]:
import pandas as pd

In [11]:
df = pd.read_csv(
    "s3://ecommerce-lake/raw/data.csv",
    encoding="latin1",
    storage_options={
        "key": "test",
        "secret": "test",
        "client_kwargs": {
            "endpoint_url": "http://localstack:4566"
        }
    }
)

In [12]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

In [13]:
df = df.drop(['Description', 'CustomerID' ], axis=1)

In [14]:
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'], format='%m/%d/%Y %H:%M')

In [15]:
df['Revenu'] =  df['Quantity'] * df['UnitPrice']

In [16]:
df.head()

,InvoiceNo,StockCode,Quantity,InvoiceDate,UnitPrice,Country,Revenu
0,536365,85123A,6,2010-12-01 08:26:00,2.55,United Kingdom,15.30
1,536365,71053,6,2010-12-01 08:26:00,3.39,United Kingdom,20.34
2,536365,84406B,8,2010-12-01 08:26:00,2.75,United Kingdom,22.00
3,536365,84029G,6,2010-12-01 08:26:00,3.39,United Kingdom,20.34
4,536365,84029E,6,2010-12-01 08:26:00,3.39,United Kingdom,20.34